class BreedOptions {
  static const List<String> dogBreeds = [
    'Labrador Retriever',
    'Golden Retriever',
    'German Shepherd',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'Yorkshire Terrier',
    'Dachshund',
    'Siberian Husky',
    'Boxer',
    'Border Collie',
    'Australian Shepherd',
    'Shih Tzu',
    'Boston Terrier',
    'Pomeranian',
    'Australian Cattle Dog',
    'Cocker Spaniel',
    'Brittany',
    'Springer Spaniel',
    'Mastiff',
    'Cane Corso',
    'Great Dane',
    'Chihuahua',
    'Maltese',
    'Havanese',
    'Cavalier King Charles Spaniel',
    'French Bulldog',
    'Bernese Mountain Dog',
    'Weimaraner',
    'Collie',
    'Basset Hound',
    'Newfoundland',
    'Saint Bernard',
    'Bloodhound',
    'Rhodesian Ridgeback',
    'Vizsla',
    'Whippet',
    'Greyhound',
    'Afghan Hound',
    'Saluki',
    'Irish Setter',
    'English Setter',
    'Gordon Setter',
    'Pointer',
    'Chesapeake Bay Retriever',
    'Flat-Coated Retriever',
    'Nova Scotia Duck Tolling Retriever',
    'Weimaraner',
    'Pharaoh Hound',
    'Basenji',
    'Akita',
    'Shiba Inu',
    'Chow Chow',
    'Shar Pei',
    'Dalmatian',
    'Great Pyrenees',
    'Anatolian Shepherd',
    'Tibetan Mastiff',
    'Komondor',
    'Puli',
    'Standard Schnauzer',
    'Giant Schnauzer',
    'Miniature Schnauzer',
    'Wire Fox Terrier',
    'Smooth Fox Terrier',
    'Jack Russell Terrier',
    'Parson Russell Terrier',
    'Scottish Terrier',
    'West Highland White Terrier',
    'Cairn Terrier',
    'Bull Terrier',
    'Staffordshire Bull Terrier',
    'American Staffordshire Terrier',
    'Pit Bull Terrier',
    'Airedale Terrier',
    'Welsh Terrier',
    'Lakeland Terrier',
    'Bedlington Terrier',
    'Kerry Blue Terrier',
    'Soft Coated Wheaten Terrier',
    'Irish Wolfhound',
    'Scottish Deerhound',
    'Borzoi',
    'Italian Greyhound',
    'Chinese Crested',
    'Xoloitzcuintli',
    'Peruvian Inca Orchid',
    'American Hairless Terrier',
    'Mixed Breed',
    'Unknown',
  ];

  static const List<String> catBreeds = [
    'Persian',
    'Maine Coon',
    'Ragdoll',
    'British Shorthair',
    'Siamese',
    'Abyssinian',
    'Birman',
    'Oriental Shorthair',
    'Sphynx',
    'Devon Rex',
    'Cornish Rex',
    'Scottish Fold',
    'American Shorthair',
    'Russian Blue',
    'Manx',
    'Norwegian Forest Cat',
    'Siberian',
    'Turkish Angora',
    'Burmese',
    'Tonkinese',
    'Balinese',
    'Javanese',
    'Himalayan',
    'Exotic Shorthair',
    'Selkirk Rex',
    'LaPerm',
    'Bombay',
    'Chartreux',
    'Korat',
    'Egyptian Mau',
    'Ocicat',
    'Bengal',
    'Savannah',
    'Munchkin',
    'Singapura',
    'Somali',
    'Turkish Van',
    'Ragamuffin',
    'Nebelung',
    'Pixie-Bob',
    'American Bobtail',
    'Japanese Bobtail',
    'Kurilian Bobtail',
    'American Curl',
    'Highlander',
    'Chausie',
    'Safari',
    'Serengeti',
    'Toyger',
    'Domestic Shorthair',
    'Domestic Longhair',
    'Mixed Breed',
    'Unknown',
  ];

  static List<String> getBreedsForPetType(String petType) {
    switch (petType.toLowerCase()) {
      case 'dog':
        return dogBreeds;
      case 'cat':
        return catBreeds;
      default:
        return [...dogBreeds, ...catBreeds];
    }
  }

  static List<String> filterBreeds(String query, String petType) {
    final breeds = getBreedsForPetType(petType);
    if (query.isEmpty) return breeds;
    
    return breeds
        .where((breed) => breed.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }
}
